#!name=Apple WLOC 定位修改
#!desc=修改 Apple 网络定位返回坐标 | 自托管选点页面: https://wloc-zhangsan-nb.pages.dev/ | 快捷指令请按 README 自建
#!author=Yu9191 Rewrite
#!homepage=https://github.com/zhangsan-nb/wloc

[rewrite_local]
^https?:\/\/gs-loc(-cn)?\.apple\.com\/clls\/wloc url script-response-body https://raw.githubusercontent.com/zhangsan-nb/wloc/refs/heads/main/dist/wloc.js
^https?:\/\/gs-loc(-cn)?\.apple\.com\/wloc-settings\/save url script-echo-response https://raw.githubusercontent.com/zhangsan-nb/wloc/refs/heads/main/dist/wloc-settings.js

[mitm]
hostname = gs-loc.apple.com, gs-loc-cn.apple.com
